learn_django/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('polls/',include('polls.urls'))
]

polls/urls.py
from django.urls import path
from . import views

app_name="polls"
urlpatterns = [
    # path("",views.index,name="index"),
    # path("<int:question_id>/",views.detail,name='detail'),
    # path("<int:question_id>/results/",views.results,name="results"),
    # path("<int:question_id>/vote/",views.vote, name="vote"),
    # path("class/",views.Hello_Nepal.as_view(),name="index")
    path("",views.IndexView.as_view(),name='index'),
    path("<int:pk>/",views.DetailView.as_view(),name='detail'),
    path("<int:pk>/results/",views.ResultsView.as_view(),name='results'),
    path("<int:question_id>/votes/",views.votes,name='votes'),
] 

polls/models.py
import datetime 
from django.db import models
from django.contrib import admin
# from datetime import timezone
from django.utils import timezone 
# Create your models here.
class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date=models.DateTimeField("data pubished")
    
    def __str__(self):
        return self.question_text
    @admin.display(
        boolean=False,
        ordering="pub_date",
        description="Published recently?"
    )
    def was_published_recently(self):
        # return self.pub_date>=timezone.now()-datetime.timedelta(days=1)
        now = timezone.now()
        return now - datetime.timedelta(days=1)<=self.pub_date <=now
    
class Choice(models.Model):
    question = models.ForeignKey(Question,on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)
    
    def __str__(self):
        return self.choice_text

polls/views.py
from django.db.models import F
# from django.template import loader
from django.shortcuts import get_object_or_404, render
from django.http import  HttpResponse,HttpResponseRedirect
from django.views import View
from .models import Question,Choice
from django.urls import reverse
from django.views import generic
from django.utils import timezone
# Create your views here.

class IndexView(generic.ListView):
    template_name = "polls/index.html"
    context_object_name = "latest_question_list"
    
    def get_queryset(self):
        """
        Return the last five published questions.
        """
        # return Question.objects.order_by("pub_date")[:5]
        return Question.objects.filter(pub_date__lte=timezone.now()).order_by("-pub_date")[:5]

class DetailView(generic.DetailView):
    model = Question
    template_name = "polls/details.html"
    def get_queryset(self):
         return Question.objects.filter(pub_date__lte=timezone.now())

class ResultsView(generic.DetailView):
    model=Question
    template_name = "polls/results.html"
    
def votes(request,question_id):
        question = get_object_or_404(Question,pk=question_id)
        try:
            selected_choice = question.choice_set.get(pk=request.POST['choice'])
        except (KeyError,Choice.DoesNotExist):
            return render(
                request,
                'polls/details.html',
                {
                    "question":question,
                    "error_message":"You didnt select a choice.",
                }
            )
        else:
            selected_choice.votes = F("votes")+1
            selected_choice.save()
            return HttpResponseRedirect(reverse("polls:results",args=(question.id,)))
        
    

















# def index(request):
#     return HttpResponse("Hello")

# class Hello_Nepal(View):
#     def get(self,request):
#         return HttpResponse("Hello from class!")
    
# # def detail(request,question_id):
# #     return HttpResponse("You are looking at question %s."% question_id)

# def results(request,question_id):
#     question = get_object_or_404(Question,pk=question_id)
#     return render(request,"results.html",{"question":question})

# def vote(request,question_id):
#     question = get_object_or_404(Question,pk=question_id)
#     try:
#         selected_choice = question.choice_set.get(pk=request.POST['choice'])
#     except (KeyError,Choice.DoesNotExist):
#         return render(
#             request,
#             'details.html',
#             {
#                 "question":question,
#                 "error_message":"You didnt select a choice.",
#             }
#         )
#     else:
#         selected_choice.votes = F("votes")+1
#         selected_choice.save()
#         return HttpResponseRedirect(reverse("polls:results",args=(question.id,)))

# def index(request):
#     latest_question_list = Question.objects.order_by("pub_date")[:5]
#     # template = loader.get_template("index.html")
#     context = {"latest_question_list":latest_question_list}
#     # return HttpResponse(template.render(context,request))
#     return render(request,"index.html",context)

# def detail(request, question_id):
#     try:
#         question = Question.objects.get(pk=question_id)
#     except Question.DoesNotExist:
#         raise Http404("Question does not exist")
#     return render(request, "details.html", {"question": question})


# def detail(request, question_id):
#     question = get_object_or_404(Question, pk=question_id)
#     return render(request,'details.html',{'question':question})

polls/templates/polls/details.html
<!doctype html>
<html lang="en">
    <head>
        <meta charset="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <title>Details</title>
    </head>
    <body>
        <form action="{% url 'polls:votes' question.id %}" method="post">
            {% csrf_token %}
            <fieldset>
                <legend><h1>{{ question.question_text }}</h1></legend>
                {% if error_message %}
                <p><strong>{{ error_message }}</strong></p>
                {% endif %} {% for choice in question.choice_set.all %}
                <input
                    type="radio"
                    name="choice"
                    id="choice{{ forloop.counter }}"
                    value="{{ choice.id }}"
                />
                <label for="choice{{ forloop.counter }}"
                    >{{ choice.choice_text }}</label
                ><br />
                {% endfor %}
            </fieldset>
            <input type="submit" value="Vote" />
        </form>
    </body>
</html>

polls/templates/polls/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=\, initial-scale=1.0">
    <title>Document</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'polls/style.css' %}">
</head>
<body>
{% if latest_question_list %}
<ul>
    {%for question in latest_question_list%}
    <li><a href="{% url 'polls:detail' question.id %}">{{ question.question_text }}</a></li>
    {%endfor%}
</ul>
{% else %}
<p>No polls are available.</p>
{% endif %}
</body>
</html>

polls/templates/polls/results.html
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<title>Document</title>
</head>
<body>
    <h1>
        {{ question.question_text }}
    </h1>
    <ul>
        {% for choice in question.choice_set.all %}
        <li>{{choice.choice_text}} -- {{choice.votes}} vote{{choice.votes|pluralize}}</li>
        {%endfor%}
    </ul>
    <a href="{% url 'polls:detail' question.id %}">Vote again?</a>
</body>
</html>